# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_ema_last <- function(values, times, tau) {
    .Call(`_utsOperators_C_ema_last`, values, times, tau)
}

C_ema_linear <- function(values, times, tau) {
    .Call(`_utsOperators_C_ema_linear`, values, times, tau)
}

C_ema_next <- function(values, times, tau) {
    .Call(`_utsOperators_C_ema_next`, values, times, tau)
}

C_rolling_central_moment <- function(values, times, width_before, width_after, m) {
    .Call(`_utsOperators_C_rolling_central_moment`, values, times, width_before, width_after, m)
}

C_rolling_max <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_max`, values, times, width_before, width_after)
}

C_rolling_mean <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_mean`, values, times, width_before, width_after)
}

C_rolling_median <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_median`, values, times, width_before, width_after)
}

C_rolling_min <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_min`, values, times, width_before, width_after)
}

C_rolling_num_obs <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_num_obs`, values, times, width_before, width_after)
}

C_rolling_product <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_product`, values, times, width_before, width_after)
}

C_rolling_sd <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_sd`, values, times, width_before, width_after)
}

C_rolling_sum <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_sum`, values, times, width_before, width_after)
}

C_rolling_sum_stable <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_sum_stable`, values, times, width_before, width_after)
}

C_rolling_var <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_rolling_var`, values, times, width_before, width_after)
}

C_sma_last <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_sma_last`, values, times, width_before, width_after)
}

C_sma_linear <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_sma_linear`, values, times, width_before, width_after)
}

C_sma_next <- function(values, times, width_before, width_after) {
    .Call(`_utsOperators_C_sma_next`, values, times, width_before, width_after)
}

